import { StyleSheet } from 'react-native';
import { fixed, r, radius, space, type } from '@unif/react-native-design';
import type { ColorTokens, ShadowTokens } from '@unif/react-native-design';
import { COMPOSER_ACTION_VISUAL_SIZE } from './constants';

export const createStyles = (colors: ColorTokens, shadows: ShadowTokens) =>
  StyleSheet.create({
    root: { position: 'relative', minWidth: 0 },
    card: {
      borderRadius: r(20),
      borderWidth: 0.5,
      borderColor: colors.outline,
      backgroundColor: colors.surface,
      ...shadows.card,
    },
    accessory: { padding: space[3] },
    header: {
      padding: space[2],
      borderBottomWidth: 0.5,
      borderBottomColor: colors.outlineVariant,
    },
    plainHeader: {
      borderBottomWidth: 0,
      paddingHorizontal: r(8),
      paddingTop: r(8),
      paddingBottom: r(4),
    },
    regular: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: space[1],
      paddingVertical: space[1],
      paddingHorizontal: space[2],
    },
    expanded: { flexDirection: 'column', alignItems: 'stretch', gap: 0 },
    hidden: { display: 'none' },
    input: {
      flex: 1,
      minWidth: 0,
      alignSelf: 'stretch',
      justifyContent: 'center',
    },
    inputExpanded: { flex: 0, width: '100%' },
    // 保持原生堆叠特征稳定，避免聚焦展开时重排输入所在的原生视图树。
    more: { width: fixed.hitTarget, height: fixed.hitTarget, zIndex: 1 },
    moreExpanded: {
      position: 'absolute',
      left: space[2],
      bottom: space[1],
    },
    toolbar: { flexDirection: 'row', alignItems: 'center' },
    toolbarExpanded: {
      width: '100%',
      minHeight: fixed.hitTarget,
      justifyContent: 'flex-end',
    },
    toolbarWithMore: { paddingStart: fixed.hitTarget + space[1] },
    trailingActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[1],
      marginStart: 'auto',
    },
    action: {
      width: fixed.hitTarget,
      height: fixed.hitTarget,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionVisual: {
      width: COMPOSER_ACTION_VISUAL_SIZE,
      height: COMPOSER_ACTION_VISUAL_SIZE,
      borderRadius: COMPOSER_ACTION_VISUAL_SIZE / 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionPressed: { backgroundColor: colors.surfaceContainerHigh },
    actionDisabled: { opacity: 0.4 },
    primary: { backgroundColor: colors.primary },
    primaryPressed: { backgroundColor: colors.primaryPressed },
    primaryDisabled: { backgroundColor: colors.surfaceContainerHighest },
    cancel: { backgroundColor: colors.surfaceContainer },
    backdrop: {
      position: 'absolute',
      bottom: '100%',
      left: 0,
      right: 0,
      zIndex: 1,
    },
    menu: {
      position: 'absolute',
      bottom: '100%',
      left: space[6],
      marginBottom: space[2],
      zIndex: 2,
    },
    voice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[3],
      paddingVertical: space[1],
      paddingHorizontal: space[2],
      borderRadius: radius['3xl'],
      backgroundColor: colors.primaryContainerSubtle,
      borderWidth: 0.5,
      borderColor: colors.brandTint14,
    },
    transcript: {
      flex: 1,
      minWidth: 0,
      color: colors.foreground,
      fontSize: type.body,
    },
    voiceBody: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[4],
      minHeight: r(34),
    },
    wave: { flexDirection: 'row', alignItems: 'center', gap: 3, height: r(20) },
    waveBar: { width: 2.5, borderRadius: 1.5, backgroundColor: colors.primary },
    transcriptPlaceholder: { color: colors.foregroundSubtle },
  });
