import { StyleSheet } from 'react-native';
import { fixed, r, radius, space, type } from '@unif/react-native-design';
import type { ColorTokens, ShadowTokens } from '@unif/react-native-design';
import {
  COMPOSER_ACTION_VISUAL_SIZE,
  COMPOSER_MENU_ICON_CONTAINER_SIZE,
} from './constants';

export const createStyles = (colors: ColorTokens, shadows: ShadowTokens) =>
  StyleSheet.create({
    root: { position: 'relative', minWidth: 0 },
    card: {
      borderRadius: r(20),
      borderWidth: 0.5,
      borderColor: colors.outline,
      backgroundColor: colors.surface,
      ...shadows.card,
    },
    accessory: { padding: space[3] },
    regular: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: space[1],
      paddingVertical: space[1],
      paddingHorizontal: space[2],
    },
    expanded: { flexDirection: 'column', alignItems: 'stretch', gap: 0 },
    hidden: { display: 'none' },
    input: { flex: 1, minWidth: 0 },
    inputExpanded: { flex: 0, width: '100%' },
    more: { width: fixed.hitTarget, height: fixed.hitTarget },
    moreExpanded: {
      position: 'absolute',
      left: space[2],
      bottom: space[1],
      zIndex: 1,
    },
    toolbar: { flexDirection: 'row', alignItems: 'center' },
    toolbarExpanded: {
      width: '100%',
      minHeight: fixed.hitTarget,
      justifyContent: 'flex-end',
    },
    toolbarWithMore: { paddingStart: fixed.hitTarget + space[1] },
    trailingActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[1],
      marginStart: 'auto',
    },
    action: {
      width: fixed.hitTarget,
      height: fixed.hitTarget,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionVisual: {
      width: COMPOSER_ACTION_VISUAL_SIZE,
      height: COMPOSER_ACTION_VISUAL_SIZE,
      borderRadius: COMPOSER_ACTION_VISUAL_SIZE / 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionPressed: { backgroundColor: colors.surfaceContainerHigh },
    actionDisabled: { opacity: 0.4 },
    primary: { backgroundColor: colors.primary },
    primaryPressed: { backgroundColor: colors.primaryPressed },
    primaryDisabled: { backgroundColor: colors.surfaceContainerHighest },
    cancel: { backgroundColor: colors.surfaceContainer },
    backdrop: {
      position: 'absolute',
      bottom: '100%',
      left: 0,
      right: 0,
      zIndex: 1,
    },
    menu: {
      position: 'absolute',
      bottom: '100%',
      left: space[6],
      width: r(200),
      maxWidth: '100%',
      marginBottom: space[2],
      borderRadius: r(20),
      borderWidth: 0.5,
      borderColor: colors.outline,
      backgroundColor: colors.surface,
      zIndex: 2,
      ...shadows.card,
    },
    menuClip: {
      borderRadius: r(20),
      overflow: 'hidden',
      paddingVertical: space[2],
    },
    menuRow: {
      minHeight: fixed.hitTarget,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[5],
      paddingVertical: space[3],
      paddingHorizontal: space[6],
    },
    menuRowPressed: { backgroundColor: colors.surfaceContainer },
    menuIcon: {
      width: COMPOSER_MENU_ICON_CONTAINER_SIZE,
      height: COMPOSER_MENU_ICON_CONTAINER_SIZE,
      borderRadius: COMPOSER_MENU_ICON_CONTAINER_SIZE / 2,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceContainer,
    },
    menuLabel: {
      flex: 1,
      minWidth: 0,
      fontSize: type.body,
      color: colors.foreground,
    },
    voice: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[2],
      paddingVertical: space[1],
      paddingHorizontal: space[2],
      borderRadius: radius['3xl'],
      backgroundColor: colors.primaryContainerSubtle,
    },
    transcript: {
      flex: 1,
      minWidth: 0,
      color: colors.foreground,
      fontSize: type.body,
    },
    transcriptPlaceholder: { color: colors.foregroundSubtle },
  });
