import { StyleSheet } from 'react-native';
import {
  fontMono,
  fw,
  icon,
  r,
  radius,
  space,
  type,
} from '@unif/react-native-design';
import type { ColorTokens } from '@unif/react-native-design';
import {
  ATTACHMENT_STATUS_OWNER_SIZE,
  ATTACHMENT_STATUS_SIZE,
  ATTACHMENT_REMOVE_OWNER_SIZE,
  CARD_WIDTH,
} from './constants';

export const createStyles = (colors: ColorTokens) =>
  StyleSheet.create({
    root: { minWidth: 0 },
    collection: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      gap: space[3],
    },
    carousel: { gap: space[3], alignItems: 'flex-start' },
    tileOwner: { position: 'relative', minWidth: 0 },
    tile: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.outline,
      borderRadius: radius.md,
      backgroundColor: colors.surfaceContainerHigh,
      overflow: 'hidden',
    },
    tileFailed: { borderColor: colors.error, borderWidth: 2 },
    documentName: {
      position: 'absolute',
      left: space[1],
      right: space[1],
      bottom: space[1],
      fontSize: type.micro,
      color: colors.foreground,
      textAlign: 'center',
      backgroundColor: colors.surfaceContainerHigh,
    },
    item: {
      gap: space[4],
      padding: space[4],
      borderWidth: 1,
      borderColor: colors.outline,
      borderRadius: radius.md,
      backgroundColor: colors.surface,
    },
    row: { width: '100%', flexDirection: 'row', alignItems: 'center' },
    rowBody: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[4],
    },
    mixedRowBody: { gap: space[3] },
    mixedRow: {
      height: r(64),
      paddingVertical: 0,
      paddingHorizontal: space[3],
      borderWidth: StyleSheet.hairlineWidth,
      borderRadius: radius.md,
      backgroundColor: colors.surfaceContainerHigh,
    },
    content: { minWidth: 0, flexShrink: 1 },
    rowContent: { flex: 1 },
    media: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    placeholder: {
      backgroundColor: colors.surfaceContainerHigh,
      borderRadius: radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusOwner: {
      position: 'absolute',
      top: (CARD_WIDTH - ATTACHMENT_STATUS_OWNER_SIZE) / 2,
      left: (CARD_WIDTH - ATTACHMENT_STATUS_OWNER_SIZE) / 2,
      width: ATTACHMENT_STATUS_OWNER_SIZE,
      height: ATTACHMENT_STATUS_OWNER_SIZE,
      alignItems: 'center',
      justifyContent: 'center',
    },
    retryOwner: { zIndex: 3, elevation: 3 },
    statusVisual: {
      width: ATTACHMENT_STATUS_SIZE,
      height: ATTACHMENT_STATUS_SIZE,
      borderRadius: radius.pill,
      backgroundColor: colors.scrim,
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeOwner: {
      position: 'absolute',
      top: 0,
      width: ATTACHMENT_REMOVE_OWNER_SIZE,
      height: ATTACHMENT_REMOVE_OWNER_SIZE,
      paddingTop: space[1],
      zIndex: 2,
      elevation: 2,
    },
    removeVisual: {
      width: icon.xs,
      height: icon.xs,
      borderRadius: radius.pill,
      backgroundColor: colors.scrim,
      alignItems: 'center',
      justifyContent: 'center',
    },
    removeInCell: { alignItems: 'flex-end', paddingRight: space[1] },
    removeFailed: { backgroundColor: colors.error },
    caption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: space[1],
      paddingTop: space[1],
      width: CARD_WIDTH,
    },
    captionText: {
      flexShrink: 1,
      fontSize: type.micro,
      color: colors.foregroundMuted,
    },
    previewAction: { width: CARD_WIDTH, alignItems: 'center' },
    name: {
      color: colors.foreground,
      fontSize: type.xs,
      fontWeight: fw.medium,
    },
    meta: {
      color: colors.foregroundSubtle,
      fontSize: type.micro,
      marginTop: r(2),
    },
    fileMeta: { fontFamily: fontMono },
    failed: { color: colors.error },
    action: { maxWidth: '100%' },
    actions: { flexDirection: 'row', flexWrap: 'wrap', gap: space[1] },
  });
