export const PROCESSING_PROGRESS_SEPARATOR = '·';
export const PROCESSING_PROGRESS_SHINE_DURATION_MS = 1800;
export const PROCESSING_PROGRESS_SHINE_RADIUS = 2;
export const PROCESSING_PROGRESS_SHINE_PEAK = 0.85;
